-- CreateEnum
CREATE TYPE "ParticipantArchetype" AS ENUM ('DISCIPLINED_LOW_RISK', 'CONSISTENT_MEDIUM_RISK', 'HIGH_LEVERAGE_GAMBLER', 'WHALE', 'SMALL_ACCOUNT_HIGH_ROI', 'VOLUME_FARMER', 'ONE_TRADE_WONDER', 'DIVERSIFIED_TRADER', 'INACTIVE_TRADER', 'LATE_COMPETITION_SPRINTER', 'REPETITIVE_SIZE_TRADER', 'FREQUENTLY_LIQUIDATED');

-- AlterTable
ALTER TABLE "Participant" ADD COLUMN "archetype" "ParticipantArchetype";
