-- AlterEnum
ALTER TYPE "IntegrityFlagType" ADD VALUE 'REPETITIVE_INSTANT_ROUND_TRIPS';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'HIGH_TRADE_FREQUENCY';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'EXCESSIVE_AVERAGE_LEVERAGE';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'EXCESSIVE_MAX_LEVERAGE';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'ONE_TRADE_SCORE_DOMINATION';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'TINY_ACCOUNT_ROI_DISTORTION';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'EXTREME_MARKET_CONCENTRATION';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'FINAL_HOUR_ACTIVITY';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'REPEATED_NEAR_IDENTICAL_SIZES';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'EXCESSIVE_LIQUIDATION_RATE';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'POSSIBLE_VOLUME_FARMING';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'VERY_LOW_AVERAGE_DURATION';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'ECONOMICALLY_NEGLIGIBLE_TRADES';
ALTER TYPE "IntegrityFlagType" ADD VALUE 'ABRUPT_FINAL_BEHAVIOR_SHIFT';
